language: ruby
sudo: required
install: skip
script:
- bin/travis-add-source -h
- bin/travis-add-all-sources-locally
- diff -u ubuntu.json <(jq 'sort_by(.alias)' < ubuntu.json)
before_install:
  - gem install rubygems-update -v 3.4.22
